name: Format check
on:
  push:
    branches:
      - master
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
      - run: yarn install
      - run: yarn run format:check
